
import type { Metadata } from "next";

import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs' 
import { Button } from "@/components/ui/button";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from '@/components/Provider';


const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'StudyFLow App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}:  {children: React.ReactNode}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <Provider>
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <header className="flex justify-between items-center p-4 h-16">
            <div className=" text-indigo-700 font-bold text-2xl">StudyFlow</div>

            <div className="flex items-center gap-2">
                <SignedOut >
                  <Button className="bg-indigo-600 hover:bg-indigo-700 cursor-pointer">
                      <SignInButton />
                  </Button>
                  <Button className="cursor-pointer">
                      <SignUpButton />
                  </Button>
                </SignedOut>
                <SignedIn >
                  <UserButton />
                </SignedIn>

            </div>
            </header>
            {children}
          </body>

        </Provider>
      </html>
    </ClerkProvider>
  )}